version: "3.8"
services:
  dev_db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: csv
      POSTGRES_DB: csv
    ports:
      - 5433:5432
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
    extra_hosts:
      - "localhost:127.0.0.1"
